### ISSUE TITLE
private method `open' called for Thor::Sandbox::Git:Class

### ISSUE THREAD

**Issue by newtonianb** [ruby-git/ruby-git#234]
umm I'm not sure what I could have possibly screwed up in the installation but I did

```
gem install git
require 'git'
g = Git.open('/my/repo')
```

and I get

```
d:/scripts/test.thor:20:in `cmd': private method `open' called for Thor::Sandbox::Git:Class (NoMethodError)
        from C:/dev/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/dev/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/dev/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/dev/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/dev/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/runner.rb:36:in `method_missing'
        from C:/dev/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
        from C:/dev/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
        from C:/dev/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/dev/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/dev/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/dev/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/bin/thor:6:in `<top (required)>'
        from c:/dev/Ruby21-x64/bin/thor:23:in `load'
        from c:/dev/Ruby21-x64/bin/thor:23:in `<main>'
```

**Comment by bluehallu** [comment]
Happened to me by having 'ruby-git' as a require rather than 'git'. It's a different library and so you're calling Kernel.open which is private!
