### ISSUE TITLE
object.rb 308 : `new' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by www-upl** [ruby-git/ruby-git#244]
Hello,
I get an error when doing

```
g = Git.open("repo/dir", :log => Logger.new(STDOUT))
revision = "14.04.01"
arch = g.archive(revision, nil, :format => "tar")

git-1.2.9.1/lib/git/object.rb:308:in `new': undefined method `new' for nil:NilClass (NoMethodError)
from /usr/local/lib/ruby/gems/2.1.0/gems/git-1.2.9.1/lib/git/base/factory.rb:53:in `object'
from /usr/local/lib/ruby/gems/2.1.0/gems/git-1.2.9.1/lib/git/base.rb:412:in `archive'
```

14.04.01 is a valid tag
Any idea?

**Comment by anuragajwani** [comment]
I am having the same issue. Did you find a solution to your problem @www-upl ?
