### ISSUE TITLE
undefined method `[]=' for nil:NilClass:

### ISSUE THREAD

**Issue by mbaglay** [ruby-git/ruby-git#265]
Have this trace:

NoMethodError - undefined method `[]=' for nil:NilClass:
    /home/user/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/git-1.2.9.1/lib/git/lib.rb:259:in`block in process_commit_log_data'
    /home/user/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/git-1.2.9.1/lib/git/lib.rb:236:in `each'
    /home/user/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/git-1.2.9.1/lib/git/lib.rb:236:in`process_commit_log_data'
    /home/user/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/git-1.2.9.1/lib/git/lib.rb:147:in `full_log_commits'

**Comment by mbaglay** [comment]
Command git log with branch stable2 has next result:

$ git log stable2
warning: refname 'stable2' is ambiguous.
commit 3430...
...

First line is **warning: refname 'stable2' is ambiguous**. Looks like current issue is because code does not handle such cases.

This log has such first line because there are refs
3430... refs/stable2
and
07e7... refs/heads/stable2
