### ISSUE TITLE
status fails on empty/new repo

### ISSUE THREAD

**Issue by jantman** [ruby-git/ruby-git#275]
Using 1.2.9.1, the current version on rubygems:

```
2.0.0 :001 > require 'git'
 => true 
2.0.0 :002 > g = Git.init('/home/jantman/tmp/foo')
 => #<Git::Base:0x000000020fc0d8 @logger=nil, @working_directory=#<Git::WorkingDirectory:0x0000000171ff88 @path="/home/jantman/tmp/foo">, @repository=#<Git::Repository:0x0000000171f1c8 @path="/home/jantman/tmp/foo/.git">, @index=#<Git::Index:0x0000000171fd08 @path="/home/jantman/tmp/foo/.git/index">> 
2.0.0 :003 > g.status
Git::GitExecuteError: git '--git-dir=/home/jantman/tmp/foo/.git' '--work-tree=/home/jantman/tmp/foo' diff-index 'HEAD'  2>&1:fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
        from /home/jantman/foo/vendor/ruby/2.0.0/gems/git-1.2.9.1/lib/git/lib.rb:917:in `command'
        from /home/jantman/foo/vendor/ruby/2.0.0/gems/git-1.2.9.1/lib/git/lib.rb:846:in `command_lines'
        from /home/jantman/foo/vendor/ruby/2.0.0/gems/git-1.2.9.1/lib/git/lib.rb:929:in `diff_as_hash'
        from /home/jantman/foo/vendor/ruby/2.0.0/gems/git-1.2.9.1/lib/git/lib.rb:381:in `diff_index'
        from /home/jantman/foo/vendor/ruby/2.0.0/gems/git-1.2.9.1/lib/git/status.rb:106:in `construct_status'
        from /home/jantman/foo/vendor/ruby/2.0.0/gems/git-1.2.9.1/lib/git/status.rb:8:in `initialize'
        from /home/jantman/foo/vendor/ruby/2.0.0/gems/git-1.2.9.1/lib/git/base/factory.rb:63:in `new'
        from /home/jantman/foo/vendor/ruby/2.0.0/gems/git-1.2.9.1/lib/git/base/factory.rb:63:in `status'
        from (irb):3
        from /home/jantman/.rvm/rubies/ruby-2.0.0-p647/bin/irb:12:in `<main>'
```

**Comment by jantman** [comment]
This is really troublesome, because it happens after I ``.add`` files too. I'm having issues with ``.add(:all => true)`` then ``.commit_all('message')`` giving me a commit with a bunch of 0-byte empty files, and a repo with all files modified. I can't even check the status between these actions, because ``status`` dies...
