### ISSUE TITLE
Git::Base#branches raises error if remote branch is checked out and locale is not en_US

### ISSUE THREAD

**Issue by dhs-rec** [ruby-git/ruby-git#753]
### Subject of the issue
When in a working copy, which only has a remote branch or tag checked out, Git::Branches errors out with `Git::UnexpectedResultError`. This doesn't happen if a local branch is checked out.

### Your environment
* git: 2.39.5
* ruby-git: 2.3.1
* ruby: 3.3.4

### Steps to reproduce
1. Clone a repository
2. Checkout a remote branch, i.e. `git checkout origin/main`
3. Run the following code inside the working copy:
```
require 'git'
g = Git.open()
g.branches
```
### Expected behaviour
Should return a list of `Git::Branch` objects

### Actual behaviour
Throws exception:
```
3.3.4 :020 > g.branches
/usr/local/rvm/gems/ruby-3.3.4@RubyTest/gems/git-2.3.1/lib/git/lib.rb:646:in `block in branches_all': Unexpected branch line format (Git::UnexpectedResultError)
        from /usr/local/rvm/gems/ruby-3.3.4@RubyTest/gems/git-2.3.1/lib/git/lib.rb:644:in `map'
        from /usr/local/rvm/gems/ruby-3.3.4@RubyTest/gems/git-2.3.1/lib/git/lib.rb:644:in `branches_all'
        from /usr/local/rvm/gems/ruby-3.3.4@RubyTest/gems/git-2.3.1/lib/git/branches.rb:13:in `initialize'
        from /usr/local/rvm/gems/ruby-3.3.4@RubyTest/gems/git-2.3.1/lib/git/base.rb:690:in `new'
        from /usr/local/rvm/gems/ruby-3.3.4@RubyTest/gems/git-2.3.1/lib/git/base.rb:690:in `branches'
        from (irb):20:in `<main>'
        from <internal:kernel>:187:in `loop'
        from /usr/local/rvm/rubies/ruby-3.3.4/lib/ruby/gems/3.3.0/gems/irb-1.13.1/exe/irb:9:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-3.3.4/bin/irb:25:in `load'
        from /usr/local/rvm/rubies/ruby-3.3.4/bin/irb:25:in `<main>'
```

**Comment by jcouball** [comment]
@dhs-rec 

I just pushed version 2.3.2 of the git gem which pinpoints the error in the error message. Please try your use case with the newer version as it might help figure out the exact scenario that cases the error you are seeing.

**Comment by dhs-rec** [comment]
@jcouball, it's the localized (German) version of `* (HEAD detached at origin/25.1)`: `* (HEAD losgelöst bei origin/25.1)` If I call `irb` like `LC_ALL=C irb`, then it works.

**Comment by jcouball** [comment]
Ok, I see the problem. This Ruby gem assumes the locale git is using is en_US. `LC_ALL=C` might be a little drastic... I wonder if `LC_ALL=en_US.UTF-8` might produce better results and still make this gem work.

In any case, sounds like we can close this issue. What do you think?

**Comment by dhs-rec** [comment]
Maybe it would be a good idea not to assume something. When I write code that parses some, possibly localized, command output, I usually set the the locale that produces the expected output. Means: the gem should IMHO set the wanted locale itself before running any git command.
